version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 2
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
