import React from 'react';
import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { api } from '~/utils/api';
import { SignIn, SignInButton, SignOutButton, useUser } from '@clerk/nextjs';
import { Box, Text, VStack, Spacer, Flex } from '@chakra-ui/react';
import CreateEvent from '~/components/Event/CreateEvent/Component';

const Home: NextPage = () => {
	const user = useUser();

	const { data, isLoading } = api.events.getAll.useQuery();

	if (isLoading) {
		return <div>Loading...</div>;
	}

	if (!data) {
		return <div>Something went wrong!</div>;
	}

	return (
		<>
			<Head>
				<title>rsvPizza</title>
				<meta name='description' content='Generated by create-t3-app' />
			</Head>
			<Box className={styles.main} alignContent={'space-between'}>
				<Flex
					direction='column'
					minHeight='100vh'
					paddingTop={6}
					paddingBottom={6}
				>
					<Box alignSelf={'center'}>
						{!user.isSignedIn && <SignInButton />}
						{user.isSignedIn && <CreateEvent />}
					</Box>
					<Spacer mb={user.isSignedIn ? 8 : 4} />
					<VStack spacing={6} alignItems='center' flexGrow={1}>
						{data?.map((event) => (
							<Box
								key={event.id}
								bgColor={'blue.500'}
								w={'61.8%'}
								borderRadius={'md'}
								borderWidth={'1px'}
								borderColor={'gray.300'}
								p={4}
								position={'relative'}
								boxShadow={'md'}
							>
								<Text
									placeSelf={'flex-end'}
									fontWeight={'medium'}
									fontStyle={'italic'}
									position={'absolute'}
									top={2}
									right={2}
								>
									{event.date.toDateString()}
								</Text>
								<Text as={'u'} fontSize={'2xl'} fontWeight={'bold'}>
									{event.name}
								</Text>
								<Text mt={2}>{event.description}</Text>
								<Text mt={2}>Location: {event.location}</Text>
								<Text mt={2}>Reservation link: {event.slug}</Text>
								<Text mt={2} fontWeight={'medium'}>
									Attendees: {event.attendees}
								</Text>
							</Box>
						))}
					</VStack>
				</Flex>
			</Box>
		</>
	);
};

export default Home;
